apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-hellopage
#  annotations:
#    "store.halo.run/app-id": ""
spec:
  displayName: HelloPage
  author:
    name: Anye
    website: "https://www.anye.xyz"
  description: 基于 Halo 的导航主题
  logo: "https://www.halo.run/logo"
  homepage: "https://github.com/Anyexyz/theme-hellopage#readme"
  repo: "https://github.com/Anyexyz/theme-hellopage"
  issues: "https://github.com/Anyexyz/theme-hellopage/issues"
  settingName: "theme-hellopage-setting"
  configMapName: "theme-hellopage-configMap"
  version: "1.0.0"
  requires: ">=2.14.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Anyexyz/theme-hellopage/blob/main/LICENSE"
